# Challenge 3 - Advanced Classification and Evaluation Metrics

Welcome to challenge #3! You know the drill by now i.e., the MCQ section and the code challenge section.

Good luck! :)

## Section 1: Multiple Choice Questions

### Q1. Which statement is **true** regarding **precision** in a multi-class classification context? (1 point)

**Options**:  
1. Precision is the fraction of actual positives that were predicted positive.  
2. Precision is the fraction of predicted positives that are actual positives.  
3. Precision is the fraction of negative predictions that are correct.

In [6]:
def answer_q1():
    """
    Q1: Which statement is **true** regarding **precision** in a multi-class classification context? (1 point)
    """

    options = {
        1: "Precision is the fraction of actual positives that were predicted positive",
        2: "Precision is the fraction of predicted positives that are actual positives",
        3: "Precision is the fraction of negative predictions that are correct"
    }

    # TODO: return the correct option number
    return options[2]

print(f'Q1: Which statement is **true** regarding **precision** in a multi-class classification context? (1 point)\nAnswer: {answer_q1()}')

Q1: Which statement is **true** regarding **precision** in a multi-class classification context? (1 point)
Answer: Precision is the fraction of predicted positives that are actual positives


### Q2. Which statement correctly describes the confusion matrix in a multi-class setting? (1 point)
**Options:**
1. It’s only valid for binary classification, not used for multi-class.
2. It’s an NxN array for N classes, comparing predicted vs. actual class labels.
3. It only shows the total correct vs. total incorrect predictions, no class breakdown.

In [7]:
def answer_q2():
    """
    Q2: Which statement correctly describes the confusion matrix in a multi-class setting? (1 point)
    """

    options = {
        1: "It’s only valid for binary classification, not used for multi-class",
        2: "It’s an NxN array for N classes, comparing predicted vs. actual class labels",
        3: "It only shows the total correct vs. total incorrect predictions, no class breakdown"
    }

    # TODO: return the correct option number
    return options[2]

print(f'Q2: Which statement correctly describes the confusion matrix in a multi-class setting?\nAnswer: {answer_q2()}')

Q2: Which statement correctly describes the confusion matrix in a multi-class setting?
Answer: It’s an NxN array for N classes, comparing predicted vs. actual class labels


### Q3. Which classifier typically uses bagging plus random subsets of features to reduce variance? (1 point)
**Options:**
1. Decision Tree
2. Random Forest
3. Naive Bayes

In [8]:
def answer_q3():
    """
    Q3: Which classifier typically uses bagging plus random subsets of features to reduce variance? (1 point)
    """

    options = {
        1: "Decision Tree",
        2: "Random Forest",
        3: "Naive Bayes"
    }

    return options[2]

print(f'Q3: Which classifier typically uses bagging plus random subsets of features to reduce variance?\nAnswer: {answer_q3()}')

Q3: Which classifier typically uses bagging plus random subsets of features to reduce variance?
Answer: Random Forest


### Q4. If we see a high recall but low precision for a certain class, what does that usually imply? (1 point)
**Options:**
1. The model rarely finds actual positives for that class.
2. The model finds most actual positives (few false negatives), but also mislabels many negatives as that class (many false positives).
3. The model completely fails to detect that class at all.

In [9]:
def answer_q4():
    """
    Q3: If we see a high recall but low precision for a certain class, what does that usually imply? (1 point)
    """

    options = {
        1: "The model rarely finds actual positives for that class",
        2: "The model finds most actual positives (few false negatives), but also mislabels many negatives as that class (many false positives)",
        3: "The model completely fails to detect that class at all"
    }

    # TODO: return the correct option number
    return options[2]

print(f'Q3: If we see a high recall but low precision for a certain class, what does that usually imply?\nAnswer: {answer_q4()}')

Q3: If we see a high recall but low precision for a certain class, what does that usually imply?
Answer: The model finds most actual positives (few false negatives), but also mislabels many negatives as that class (many false positives)


---

## Section 2: Code challenge (5 points)

For this code challenge, you will work with the [UCI Car Evaluation dataset](https://www.kaggle.com/datasets/elikplim/car-evaluation-data-set). A summary of the dataset is as follows.

### Features:
- **buying**: Buying price of the car (vhigh, high, med, low)
- **maint**: Price of the maintenance (vhigh, high, med, low)
- **doors**: Number of doors (2, 3, 4, 5more)
- **persons**: Capacity in terms of persons to carry (2, 4, more)
- **lug_boot**: Size of the luggage boot (small, med, big)
- **safety**: Estimated safety of the car (low, med, high)

### Class Labels:
- **unacc**: Unacceptable
- **acc**: Acceptable
- **good**: Good
- **vgood**: Very Good

To pass this section of the weekly challenge, uncomment/fill in code where necessary (marked with a 'TODO:' comment).

In [10]:
# Common imports
import numpy as np
import pandas as pd
from sklearn.preprocessing import OneHotEncoder, LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
# from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import precision_score, recall_score
from sklearn.metrics import classification_report, confusion_matrix

### 1. Load & Encode Car Dataset (1 point)

**Goals** for `load_and_encode_car_data()`
1. Reads car.csv.
2. Encodes 6 features (buying, maint, doors, persons, lug_boot, safety).
    e.g. one-hot or custom mapping.
3. Maps class -> integer: unacc=0, acc=1, good=2, vgood=3.
4. Returns (X, y) as arrays.

In [11]:
def load_and_encode_car_data():
    """
    1) read 'car.csv'
    2) encode the 6 features to numeric or one-hot
    3) map class to {0,1,2,3}
    4) return X, y
    """
    df = pd.read_csv("car.csv")

    le = LabelEncoder()

    for cat_var in ['buying', 'maint', 'lug_boot', 'doors', 'persons', 'safety']:
        df[cat_var] = le.fit_transform(df[cat_var])  

    # replacing values
    df['class'].replace(['unacc', 'acc', 'good', 'vgood'],
                    [0,1,2,3], inplace=True)


    return df[['buying', 'maint', 'lug_boot', 'doors', 'persons', 'safety']], df['class']
    
    
# demonstration
# X, y = load_and_encode_car_data()
# print("Shapes:", X.shape, y.shape)

### 2. Train Baseline Model (1 point)

**Goals** for `train_baseline_model(X, y)`:
1. Split data (test_size=0.2, random_state=42).
2. Use a simple classifier (logistic or naive_bayes, etc.).
3. Return (model, X_test, y_test, y_pred).

In [12]:
def train_classifier(X, y):
    """
    1. split X,y
    2. pick a classifier
    3. fit & predict 
    4. return (model, X_test, y_test, y_pred)
    """
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
    clf = RandomForestClassifier()
    clf.fit(X_train, y_train)
    y_pred = clf.predict(X_test)
    
    return clf, X_test, y_test, y_pred

### 3. Generate Confusion Matrix (1 point)

**Goals**:
1.  `generate_confmatrix(y_true, y_pred)` → returns an NxN confusion matrix array from scikit-learn

In [13]:
def generate_confmatrix(y_true, y_pred):
    """
    Return confusion_matrix array (sklearn).
    """
    return confusion_matrix(y_true, y_pred)
    

### 4. Compute F1 score (1 point)

**Goals** for `manual_f1_for_class(y_true, y_pred, class_idx)`:
1. Use scikit-learn to get precision, recall for that single class, e.g. by calling `precision_score(..., labels=[class_idx], average='macro')` or `average='binary'` approach.
2. Then manually compute F1 using the formula (no direct scikit calls for F1).
3. Return the F1 score.


In [14]:
def manual_f1_for_class(y_true, y_pred, class_idx):
    """
    1) use scikit to get precision, recall for 'class_idx' only
    2) compute f1 score manually
    return that float
    """
    precision = precision_score(y_true, y_pred, average='macro', labels=[class_idx])
    recall = recall_score(y_true, y_pred, labels=[class_idx], average='macro')
    f1 = 2 * (precision * recall) / (precision + recall)
    return f1

### 5. Generate Classification Report (1 point)

**Goals**

1. Generate a classification report for your trained model and return the report (string value).

In [15]:
def generate_classification_report(y_true, y_pred):
    """
    calls sklearn's classification_report
    returns it
    """
    return classification_report(y_true, y_pred)

# optional demonstration
X, y = load_and_encode_car_data()
model, X_te, y_te, y_pr = train_classifier(X,y)
print("Generate confmatrix:")
cm = generate_confmatrix(y_te, y_pr)
print(cm)
f1class0 = manual_f1_for_class(y_te, y_pr, class_idx=0)
print("F1 for class 0 manually:", f1class0)
rep = generate_classification_report(y_te, y_pr)
print(rep)


Generate confmatrix:
[[235   0   0   0]
 [  5  71   7   0]
 [  0   0  11   0]
 [  0   1   0  16]]
F1 for class 0 manually: 0.9894736842105264
              precision    recall  f1-score   support

           0       0.98      1.00      0.99       235
           1       0.99      0.86      0.92        83
           2       0.61      1.00      0.76        11
           3       1.00      0.94      0.97        17

    accuracy                           0.96       346
   macro avg       0.89      0.95      0.91       346
weighted avg       0.97      0.96      0.96       346



/tmp/ipykernel_27177/3935847903.py:16: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['class'].replace(['unacc', 'acc', 'good', 'vgood'],
/tmp/ipykernel_27177/3935847903.py:16: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['class'].replace(['unacc', 'acc', 'good', 'vgood'],
